// ============================================================
// DATA-RECIPES — locked full-batch recipe catalog
//
// _ingredients  locked at Phase 1 (gram-standardized from source URL)
// _totalMacros  locked at Phase 2 (USDA FoodData Central)
// lastUsedWeek  runtime only — updated by engine on plan confirm
//
// Serving division formula (computed in engine.js):
//   N = Math.round(calories / 650)
//   N = Math.min(Math.max(N, 1), 5)
//   if (calories / N < 400) N = Math.max(N - 1, 1)
//
// Rank / cooldown: A = 2wk, B = 4wk, C = 10wk
//
//============================================================

const RECIPE_CATALOG = {

  '20minute_tofu_stirfry': {
    name: '20-Minute Tofu Stir-Fry',
    servings: 2,
    rank: 'C',
    _ingredients: [
      { id: 'dry brown rice', qty: '1 cup' },
      { id: 'extra firm tofu, pressed and crumbled or cubed*', qty: '1 cup' },
      { id: 'coconut aminos', qty: '1 Tbsp' },
      { id: 'chili garlic sauce (optional)', qty: '1 tsp' },
      { id: 'sesame oil (if avoiding oil, sub water or use a non-stick pan)', qty: '2 tsp' },
      { id: 'peanut butter (or other nut butter)', qty: '2 Tbsp' },
      { id: '2-3 Tbsp coconut aminos / tamari', qty: '' },
      { id: 'maple syrup', qty: '1 Tbsp' },
      { id: 'lime juice', qty: '1 Tbsp' },
      { id: '1-2 tsp chili garlic sauce', qty: '' },
      { id: 'sesame oil (if avoiding oil, sub water or use a non-stick pan)', qty: '2 tsp' },
      { id: 'chopped shiitake mushrooms', qty: '1 cup' },
      { id: 'thinly sliced red cabbage', qty: '1 cup' },
      { id: 'thinly sliced red bell pepper', qty: '1 cup' },
      { id: 'garlic, minced', qty: '2 cloves' },
      { id: 'thinly sliced green onion', qty: '1/4 cup' },
      { id: 'fresh minced ginger', qty: '1 Tbsp' },
      { id: 'Lime wedges', qty: '' },
      { id: 'Fresh cilantro, chopped', qty: '' },
      { id: 'Peanut sauce', qty: '' },
      { id: 'Chili Garlic Sauce or Sriracha (we like Huy Fong Foods brand)', qty: '' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  '30minute_mediterranean_chicken_bowls': {
    name: '30-Minute Mediterranean Chicken Bowls',
    servings: 4,
    rank: 'B',
    _ingredients: [
      { id: 'batch Spicy Roasted Red Pepper Feta Dip', qty: '½' },
      { id: 'extra-virgin olive oil', qty: '2 tablespoons' },
      { id: 'ground chicken (or turkey or sub beef or lamb!)', qty: '1 pound' },
      { id: 'to large yellow onion, finely diced', qty: '½ medium' },
      { id: 'kosher salt', qty: '1 teaspoon' },
      { id: 'garlic powder', qty: '1 teaspoon' },
      { id: 'cumin', qty: '1 teaspoon' },
      { id: 'dried oregano', qty: '1 teaspoon' },
      { id: 'paprika', qty: '1 teaspoon' },
      { id: 'turmeric', qty: '1 teaspoon' },
      { id: 'dried thyme', qty: '½ teaspoon' },
      { id: 'Lots of freshly ground black pepper', qty: '' },
      { id: 'cooked rice of choice (I love jasmine or brown rice!)', qty: '2 cups of' },
      { id: 'roasted chickpeas (I love Biena) or regular rinsed and drained chickpeas work too!', qty: '1 cup' },
      { id: 'Persian cucumbers, halved lengthwise and sliced', qty: '4' },
      { id: 'Pickled red onion', qty: '1/4 cup' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  '35_minute_chili_honey_garlic_salmon_bowls': {
    name: '35 Minute Chili Honey Garlic Salmon Bowls',
    servings: 4,
    rank: 'B',
    _ingredients: [
      { id: '(6 ounce) salmon filets, cut into bite-size chunks', qty: '4' },
      { id: 'ground ginger', qty: '1/2 teaspoon' },
      { id: 'chipotle powder or cayenne', qty: '1 teaspoon' },
      { id: 'chili flakes', qty: '1/4 tsp' },
      { id: 'extra virgin olive oil', qty: '4 tablespoons' },
      { id: 'broccoli florets or chopped asparagus or a mix', qty: '3 cups' },
      { id: 'avocado cut into wedges', qty: '1' },
      { id: 'tamari or soy sauce', qty: '1/3 cup' },
      { id: 'honey', qty: '3 tablespoons' },
      { id: 'garlic, chopped', qty: '6 cloves' },
      { id: 'ground ginger', qty: '1 teaspoon' },
      { id: '3-4 tablespoons chili paste', qty: '' },
      { id: 'chopped green onions', qty: '2 tablespoons' },
      { id: 'toasted sesame oil', qty: '1 tablespoon' },
      { id: 'mayo', qty: '1/2 cup' },
      { id: '1-2 tablespoons gochujang', qty: '' },
      { id: 'honey', qty: '2 teaspoons' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  bright_herby_lemongrass_chicken_green_curry: {
    name: 'Bright & Herby Lemongrass Chicken Green Curry',
    servings: 4,
    _ingredients: [
      { id: 'extra virgin olive oil', qty: '1 tablespoon' },
      { id: 'boneless skinless chicken breast, cubed', qty: '1 pound' },
      { id: 'kosher salt', qty: '½ teaspoon' },
      { id: 'Freshly ground black pepper', qty: '' },
      { id: 'extra virgin olive oil', qty: '1 tablespoon' },
      { id: 'fresh lemongrass', qty: '2 stalks of' },
      { id: 'scallions, sliced', qty: '4' },
      { id: 'green curry paste (Thai Kitchen)', qty: '2 tablespoons' },
      { id: 'garlic cloves, minced', qty: '3' },
      { id: 'grated fresh ginger', qty: '1 tablespoon' },
      { id: 'ground turmeric)', qty: '1 teaspoon' },
      { id: '(15-ounce) can full-fat coconut milk', qty: '1' },
      { id: 'low-sodium chicken broth (or sub water)', qty: '½ cup' },
      { id: 'low-sodium soy sauce, to taste', qty: '1 tablespoon' },
      { id: 'kosher salt, plus more as needed', qty: '½ teaspoon' },
      { id: 'to medium sweet potato, peeled and cut into ½ inch cubes', qty: '1 small' },
      { id: 'red bell pepper, diced into ½ inch pieces', qty: '1 large' },
      { id: 'frozen peas (or sub 1 cups small cauliflower florets or diced zucchini)', qty: '¾ cup' },
      { id: 'fish sauce', qty: '1 tablespoon' },
      { id: 'Juice of 1 lime', qty: '' },
      { id: 'Cooked brown rice or white rice or cooked rice noodles', qty: '' },
      { id: 'chopped mix of fresh herbs (mint, cilantro, basil, and/or Thai basil)', qty: '½ cup' },
      { id: 'sliced scallions (green part only)', qty: '¼ cup' },
      { id: 'Optional: Toasted coconut flakes/chips (or sub peanuts/cashews for crunch!)', qty: '' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  cheap_healthy_meal_prep_idea_better_than_chipotle_diy_chi: {
    name: 'Cheap & Healthy Meal Prep Idea: Better Than Chipotle DIY Chi',
    servings: 4,
    rank: 'A',
    _ingredients: [
      { id: 'boneless skinless chicken thighs (or chicken breasts will also work)', qty: '1 pound' },
      { id: 'chunky salsa', qty: '1 cup' },
      { id: 'chipotle chili powder', qty: '1/2 teaspoon' },
      { id: 'coconut oil', qty: '2 teaspoons' },
      { id: 'dry short grain brown rice', qty: '1 cup' },
      { id: 'vegetarian broth', qty: '2 cups' },
      { id: 'lime, juiced', qty: '1 small' },
      { id: 'organic sweet corn', qty: '1 cup' },
      { id: 'red onion, diced', qty: '1 small' },
      { id: 'fresh chopped cilantro', qty: '1/4 cup' },
      { id: 'lime, juiced', qty: '1 small' },
      { id: 'Freshly ground salt and black pepper, to taste', qty: '' },
      { id: '(15 oz) can low sodium black beans, rinsed and drained', qty: '1' },
      { id: 'cheddar cheese shreds', qty: '1/2 cup' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  chicken_and_rice_casserole: {
    name: 'Chicken and Rice Casserole',
    servings: 6,
    rank: 'B',
    _ingredients: [
      { id: 'dry brown rice', qty: '1½ cups' },
      { id: 'water', qty: '3 cups' },
      { id: 'chicken breast (boneless & skinless, cut in ½ -in cubes)', qty: '1' },
      { id: 'salt', qty: '1½ tsp' },
      { id: 'black pepper', qty: '1 tsp' },
      { id: 'olive oil', qty: '1 Tbsp' },
      { id: 'yellow onion (small dice)', qty: '1' },
      { id: 'carrots (peeled, small dice)', qty: '3' },
      { id: 'butter', qty: '3 Tbsp' },
      { id: 'all-purpose flour', qty: '3 Tbsp' },
      { id: 'chicken broth', qty: '1 cup' },
      { id: 'whole milk', qty: '1 cup' },
      { id: 'smoked paprika', qty: '½ tsp' },
      { id: 'garlic powder', qty: '½ tsp' },
      { id: 'onion powder', qty: '½ tsp' },
      { id: 'lb. frozen broccoli florets (thawed, cut into bite-sized pieces)', qty: '½' },
      { id: 'oz. medium cheddar cheese (shredded & divided)', qty: '8' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  chicken_lentil_soup: {
    name: 'Chicken Lentil Soup',
    servings: 6,
    rank: 'A',
    _ingredients: [
      { id: 'olive oil', qty: '1 tbsp' },
      { id: 'yellow onion (diced)', qty: '1' },
      { id: 'carrots (diced)', qty: '3' },
      { id: 'celery ribs (diced)', qty: '2' },
      { id: 'garlic cloves (chopped)', qty: '4' },
      { id: 'salt', qty: '1 tsp' },
      { id: 'smoked paprika', qty: '1 tsp' },
      { id: 'cumin', qty: '1/2 tsp' },
      { id: 'green lentils (rinsed)', qty: '1 ½ cups' },
      { id: 'lb. chicken breast (cut into bite-sized pieces)', qty: '1 ½' },
      { id: 'oz. fire roasted diced tomatoes (with their juices)', qty: '14' },
      { id: 'chicken broth', qty: '6 cups' },
      { id: 'oz. spinach', qty: '5' },
      { id: 'salt and pepper to taste', qty: '' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  classic_lentil_burgers: {
    name: 'Classic Lentil Burgers',
    servings: 10,
    rank: 'B',
    _ingredients: [
      { id: 'cooked green lentils', qty: '2 ½ cups' },
      { id: 'carrots (finely chopped)', qty: '1 cup' },
      { id: 'onion (finely chopped)', qty: '1 cup' },
      { id: 'garlic (minced)', qty: '3 cloves' },
      { id: 'walnuts', qty: '1/2 cup' },
      { id: 'sunflower seeds', qty: '1/2 cup' },
      { id: 'chickpea flour', qty: '1/2 cup' },
      { id: 'breadcrumbs (whole grain or gluten-free)', qty: '1 cup' },
      { id: 'eggs', qty: '2' },
      { id: 'tomato paste', qty: '2 tablespoons' },
      { id: 'vegan Worcestershire', qty: '2 tablespoons' },
      { id: 'fresh or dried thyme', qty: '1 tablespoon' },
      { id: 'fresh or dried oregano', qty: '1 tablespoon' },
      { id: 'fine sea salt', qty: '1 teaspoon' },
      { id: 'whole grain buns (dave\'s killer bread)', qty: '8' },
      { id: 'olive oil for cooking', qty: '' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  greek_sheetpan_chicken: {
    name: 'Greek Sheet-Pan Chicken',
    servings: 6,
    rank: 'B',
    _ingredients: [
      { id: 'fresh lemon juice Juice of 2 large lemons', qty: '1/4 cup' },
      { id: 'dried oregano', qty: '1 to 2 teaspoons' },
      { id: 'garlic clove (minced)', qty: '1 large' },
      { id: 'kosher salt', qty: '3/4 teaspoon' },
      { id: 'black pepper', qty: '3/4 teaspoon' },
      { id: 'extra virgin olive oil', qty: '3/4 cup' },
      { id: 'red onion, (halved and sliced into 1/2 -inch pieces)', qty: '1 large' },
      { id: 'zucchini, (halved and sliced into 1/2-inch pieces (half moons)', qty: '1 medium' },
      { id: 'orange bell pepper, (cored and sliced into 1/2-inch thick slices)', qty: '1 large' },
      { id: 'tomato, (cut into 8 wedges)', qty: '1 large' },
      { id: 'Kosher salt', qty: '' },
      { id: 'ground black pepper', qty: '' },
      { id: 'boneless skinless chicken thighs', qty: '6 to 8' },
      { id: 'pitted Kalamata olives', qty: '1/4 cup' },
      { id: 'pitted Castelvetrano olives', qty: '1/4 cup' },
      { id: 'ounces feta cheese, (cut into chunks)', qty: '4' },
      { id: 'chopped Italian parsley, (for garnish)', qty: '1/4 cup' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  healthy_slow_cooker_chicken_tikka_masala: {
    name: 'Healthy Slow Cooker Chicken Tikka Masala',
    servings: 4,
    rank: 'A',
    _ingredients: [
      { id: 'olive oil', qty: '1/2 tablespoon' },
      { id: 'white or yellow onion, chopped', qty: '1' },
      { id: 'jalapeño, seeds removed and finely diced', qty: '1' },
      { id: 'garlic, minced', qty: '3 cloves' },
      { id: '(28 ounce) can crushed tomatoes or tomato puree (do not use tomato sauce)', qty: '1' },
      { id: 'fresh grated ginger', qty: '1 tablespoon' },
      { id: 'lemon, juiced (about 1-2 tablespoons fresh lemon juice)', qty: '1/2' },
      { id: 'garam masala', qty: '1 tablespoon' },
      { id: 'paprika', qty: '1 teaspoon' },
      { id: 'cayenne pepper', qty: '1/2 teaspoon' },
      { id: 'ground turmeric', qty: '1/2 teaspoon' },
      { id: 'curry powder', qty: '1/2 teaspoon' },
      { id: 'Freshly ground black pepper', qty: '' },
      { id: 'salt', qty: '1/4 teaspoon' },
      { id: 'boneless skinless chicken breasts', qty: '1 1/2 pounds' },
      { id: 'light coconut milk (from the can)', qty: '1 cup' },
      { id: 'Additional salt, to taste', qty: '' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  korean_braised_tofu_dubu_jorim: {
    name: 'Korean Braised Tofu (Dubu Jorim)',
    servings: 4,
    rank: 'A',
    _ingredients: [
      { id: 'firm tofu (package size is 14oz)', qty: '1 package of' },
      { id: 'light soy sauce', qty: '1/4 cup' },
      { id: 'water', qty: '1/4 cup' },
      { id: 'gochugaru', qty: '1 tbsp' },
      { id: 'maple syrup', qty: '1/2 tbsp' },
      { id: 'sesame oil', qty: '1 tbsp' },
      { id: 'sesame seeds', qty: '1/2 tbsp' },
      { id: 'garlic (minced)', qty: '2 cloves' },
      { id: 'scallion (finely chopped)', qty: '1' },
      { id: 'avocado oil', qty: '2 tbsp' },
      { id: 'dry brown rice', qty: '1 cup' },
      { id: 'heads of broccoli, trimmed and steamed', qty: '2' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  korean_inspired_ground_turkey_bowls: {
    name: 'Korean Inspired Ground Turkey Bowls',
    servings: 4,
    rank: 'A',
    _ingredients: [
      { id: 'shredded carrots', qty: '1 cup' },
      { id: 'red onion, thinly sliced', qty: '1 cup' },
      { id: 'cucumber, thinly sliced', qty: '1 cup' },
      { id: 'rice wine vinegar', qty: '1/3 cup' },
      { id: 'water', qty: '1/2 cup' },
      { id: 'maple syrup', qty: '1 tablespoon' },
      { id: 'kosher salt', qty: '1 teaspoon' },
      { id: 'dry brown rice', qty: '1 cup of' },
      { id: 'lean ground turkey', qty: '1 lb' },
      { id: 'green onions, chopped', qty: '1 bunch of' },
      { id: 'sesame oil', qty: '2 teaspoon' },
      { id: 'minced ginger', qty: '2 teaspoon' },
      { id: 'minced garlic', qty: '2 teaspoon' },
      { id: 'low sodium soy sauce', qty: '1/4 cup' },
      { id: 'honey', qty: '3 tablespoon' },
      { id: 'rice wine vinegar', qty: '1 tablespoon' },
      { id: 'Sriracha', qty: '2 teaspoon' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  lemon_garlic_salmon_tray_bake: {
    name: 'Lemon garlic salmon tray bake',
    servings: 4,
    rank: 'B',
    _ingredients: [
      { id: 'x 6 oz salmon fillets (, skin on or off, doesn\'t matter (Note 1)', qty: '4' },
      { id: 'lemon zest', qty: '1 tsp' },
      { id: 'lemon juice', qty: '1 tbsp' },
      { id: 'extra virgin olive oil', qty: '2 tbsp' },
      { id: 'dijon mustard', qty: '1 tsp' },
      { id: 'garlic cloves (grated using microplane)', qty: '2' },
      { id: 'kosher salt', qty: '1/2 tsp' },
      { id: 'black pepper', qty: '1/4 tsp' },
      { id: 'asparagus (woody ends snapped or trimmed off)', qty: '3 bunches' },
      { id: 'cherry tomatoes', qty: '7 oz' },
      { id: 'extra virgin olive oil', qty: '2 tsp' },
      { id: 'each salt and pepper', qty: '1/4 tsp' },
      { id: 'Parmesan (finely grated)', qty: '1/4 cup' },
      { id: 'dry Quinoa', qty: '1 cup' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  lentil_loaf: {
    name: 'Lentil Loaf',
    servings: 10,
    rank: 'B',
    _ingredients: [
      { id: 'oz. white mushrooms', qty: '16' },
      { id: 'carrots', qty: '2 large' },
      { id: 'sun dried tomatoes in oil (processed very fine)', qty: '2 Tbsp' },
      { id: 'olive oil', qty: '1 Tbsp' },
      { id: 'onion (diced very small)', qty: '½ medium' },
      { id: 'sea salt', qty: '1½ tsp' },
      { id: 'black pepper (freshly cracked)', qty: '1 tsp' },
      { id: 'cooked lentils (divided)', qty: '3 cups' },
      { id: 'garlic cloves (minced)', qty: '4' },
      { id: 'walnuts (processed)', qty: '½ cups' },
      { id: 'ground flaxseed', qty: '2 Tbsp' },
      { id: 'ketchup', qty: '2 Tbsp' },
      { id: 'breadcrumbs', qty: '¼ cup' },
      { id: 'soy sauce', qty: '1 Tbsp' },
      { id: 'fresh parsley (minced)', qty: '2 Tbsp' },
      { id: 'ketchup', qty: '½ cup' },
      { id: 'brown sugar', qty: '1 Tbsp' },
      { id: 'soy sauce', qty: '1 Tbsp' },
      { id: 'Dijon mustard', qty: '1 tsp' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  marry_me_chicken_pasta: {
    name: 'Marry Me Chicken Pasta',
    servings: 6,
    rank: 'A',
    _ingredients: [
      { id: 'sundried tomato oil from jar', qty: '2 Tbsp' },
      { id: 'lb. chicken breasts (cut into 1-inch cubes, 2 breasts)', qty: '1' },
      { id: 'salt', qty: '1 tsp' },
      { id: 'black pepper', qty: '1 tsp' },
      { id: 'onion (small dice)', qty: '½' },
      { id: 'garlic cloves (minced)', qty: '4' },
      { id: 'sundried tomatoes (packed in oil, thinly sliced)', qty: '½ cup' },
      { id: 'tomato past', qty: '2 Tbsp' },
      { id: 'chicken broth (20oz.)', qty: '2½ cups' },
      { id: 'oz. chickpea penne pasta (uncooked)', qty: '8' },
      { id: 'Italian seasoning', qty: '1½ tsp' },
      { id: 'heavy cream (room temperature,, 4oz.)', qty: '½ cup' },
      { id: 'frozen spinach (thawed and pressed)', qty: '⅓ cup' },
      { id: 'Parmesan cheese (grated)', qty: '½ cup' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  one_pan_southwest_chicken_and_rice_fajita_skillet: {
    name: 'One Pan Southwest Chicken and Rice Fajita Skillet',
    servings: 6,
    rank: 'A',
    _ingredients: [
      { id: 'Spice mixture', qty: '' },
      { id: 'cumin', qty: '1 ½ teaspoons' },
      { id: 'ground coriander', qty: '1 ½ teaspoons' },
      { id: 'chili powder', qty: '1 ½ teaspoon' },
      { id: 'kosher salt', qty: '1 ½ teaspoons' },
      { id: 'paprika', qty: '1 teaspoon' },
      { id: 'oregano', qty: '1 teaspoon' },
      { id: 'garlic powder', qty: '½ teaspoon' },
      { id: 'cayenne', qty: '¼ teaspoon' },
      { id: 'Freshly ground black pepper', qty: '' },
      { id: 'For the skillet', qty: '' },
      { id: 'boneless skinless chicken thighs', qty: '1 ½ pounds' },
      { id: 'extra-virgin olive oil, divided', qty: '3 tablespoons' },
      { id: 'yellow onion, sliced', qty: '1' },
      { id: 'red bell pepper, sliced', qty: '1' },
      { id: 'orange bell pepper, sliced', qty: '1' },
      { id: 'green bell pepper, sliced', qty: '1' },
      { id: 'garlic cloves, minced', qty: '3' },
      { id: 'fresh grated turmeric (if you don\'t want yellow hands wear gloves)', qty: '1 to 2 tablespoons of' },
      { id: 'jasmine or basmati rice, rinsed and drained', qty: '1 cup' },
      { id: 'low-sodium chicken broth (or water)', qty: '1 ¾ cup' },
      { id: 'corn off the cob, from 1 large ear or corn (or use frozen or canned corn)', qty: '¾ cup' },
      { id: '(15 ounce) can black beans, drained and rinsed', qty: '1' },
      { id: 'shredded Mexican cheese blend', qty: '¾ cup' },
      { id: 'chopped fresh cilantro', qty: '⅓ cup' },
      { id: 'scallions, thinly sliced', qty: '2' },
      { id: 'For serving', qty: '' },
      { id: 'lime, cut into wedges', qty: '1' },
      { id: '(guacamole)', qty: '1/4 cup' },
      { id: 'salsa', qty: '1/4 cup' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  overnight_oats_recipes: {
    name: 'Overnight Oats Recipes',
    servings: 1,
    _ingredients: [
      { id: 'rolled oats', qty: '½ c' },
      { id: 'chia seeds', qty: '1 T' },
      { id: 'ground flax', qty: '1 T' },
      { id: 'unsweetened unflavored soy milk', qty: '1 c' },
      { id: 'cinnamon', qty: '½ tsp' },
      { id: 'maple syrup', qty: '2 tsp' },
      { id: 'blueberries', qty: '¼ c' },
      { id: 'sliced apple', qty: '1/4 c' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  sesame_ginger_sweet_teriyaki_salmon_with_garlic_quinoa_stir: {
    name: 'Sesame Ginger Sweet Teriyaki Salmon with Garlic Quinoa Stir-',
    servings: 4,
    rank: 'B',
    _ingredients: [
      { id: 'teriyaki sauce', qty: '1 cup' },
      { id: 'freshly grated ginger', qty: '1 teaspoon' },
      { id: '2-4 cloves garlic, minced', qty: '' },
      { id: 'dark brown sugar', qty: '3 tablespoons' },
      { id: 'honey', qty: '2 tablespoons' },
      { id: 'olive oil', qty: '1/4 cup' },
      { id: 'salmon', qty: '1 pound' },
      { id: 'quinoa, rinsed', qty: '3/4 cup' },
      { id: 'garlic salt', qty: '1/2 teaspoon' },
      { id: 'olive oil', qty: '1 tablespoon' },
      { id: 'red bell pepper, thinly sliced', qty: '1' },
      { id: 'yellow bell pepper, thinly sliced', qty: '1' },
      { id: 'garlic, minced', qty: '2 clove' },
      { id: 'fresh grated ginger', qty: '1 teaspoon' },
      { id: 'garlic, minced', qty: '4 cloves' },
      { id: 'sugar snap peas or snow peas', qty: '1 1/2 cups' },
      { id: 'Extras', qty: '' },
      { id: 'salt and black pepper to taste', qty: '' },
      { id: 'red pepper flakes, if desired', qty: '1/4 teaspoon' },
      { id: 'extra soy or teriyaki sauce', qty: '' },
      { id: 'sesame seeds', qty: '1 tablespoon' },
      { id: 'fresh cilantro, chopped', qty: '1/4 cup' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  sheet_pan_sesame_chicken_and_vegetables: {
    name: 'Sheet Pan Sesame Chicken and Vegetables',
    servings: 4,
    _ingredients: [
      { id: 'low-sodium soy sauce', qty: '¼ cup' },
      { id: 'honey', qty: '3 tablespoons' },
      { id: 'rice vinegar', qty: '2 tablespoons' },
      { id: 'toasted sesame oil', qty: '2 tablespoons' },
      { id: 'extra-virgin olive oil or avocado oil', qty: '1 tablespoon' },
      { id: 'sambal olek, depending on your heat tolerance', qty: '1 to 2 tablespoons' },
      { id: 'grated fresh ginger', qty: '1 tablespoon' },
      { id: 'garlic cloves, minced or grated', qty: '2' },
      { id: 'boneless skinless chicken thighs', qty: '1 ½ pounds' },
      { id: 'asparagus, ends trimmed', qty: '1 bunch of' },
      { id: 'red bell pepper, cut into 1-inch chunks', qty: '1' },
      { id: 'red onion, cut into 1-inch chunks or sliced', qty: '1' },
      { id: 'fresh torn leafy herbs (mix of cilantro, basil and mint)', qty: '¼ cup' },
      { id: 'scallions, thinly sliced', qty: '2' },
      { id: 'toasted sesame seeds (i love a mix of white and black!)', qty: '1 tablespoon' },
      { id: 'dry quinoa', qty: '1 c' },
    ],
    _totalMacros: { calories: 2619, proteinG: 228.63, fatG: 97.82, carbsG: 204.59, sodiumMg: 3452 },
  },

  slow_cooker_salsa_verde_chicken_chickpea_chili: {
    name: 'Slow Cooker Salsa Verde Chicken Chickpea Chili',
    servings: 6,
    rank: 'B',
    _ingredients: [
      { id: 'boneless skinless chicken thighs', qty: '2 pounds' },
      { id: 'mild salsa verde (trader joe\'s)', qty: '24 oz' },
      { id: 'onion, chopped', qty: '1' },
      { id: 'jalapeño, seeded and diced', qty: '1/2' },
      { id: 'garlic cloves, minced', qty: '2' },
      { id: 'frozen corn', qty: '1 cup' },
      { id: '(15 oz) can chickpeas, rinsed & drained', qty: '1' },
      { id: 'uncooked quinoa', qty: '1/2 cup' },
      { id: 'low sodium chicken broth', qty: '2 1/2 cups' },
      { id: 'lime, juiced', qty: '1 small' },
      { id: 'ground cumin', qty: '2 teaspoons' },
      { id: 'dried oregano', qty: '2 teaspoons' },
      { id: 'Salt and pepper, to taste', qty: '' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  southwest_chicken_skillet: {
    name: 'Southwest Chicken Skillet',
    servings: 4,
    rank: 'A',
    _ingredients: [
      { id: 'dry brown rice', qty: '1 cup' },
      { id: 'salsa', qty: '1 cup' },
      { id: 'chicken breast cut into <1-inch chunks', qty: '1 ½ cups' },
      { id: '15oz. can black beans', qty: '1' },
      { id: 'chili powder', qty: '1 Tbsp' },
      { id: 'chicken broth', qty: '1 3/4 cups' },
      { id: 'shredded cheese', qty: '1 cup' },
      { id: '2-3 green onions', qty: '' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  southwest_lentils_and_rice_skillet: {
    name: 'Southwest Lentils and Rice Skillet',
    servings: 4,
    rank: 'A',
    _ingredients: [
      { id: 'olive oil', qty: '1 Tbsp' },
      { id: 'red onion', qty: '1 small' },
      { id: 'garlic', qty: '2 cloves' },
      { id: 'cumin', qty: '1 ½ tsp' },
      { id: 'chili powder', qty: '1 tsp' },
      { id: 'adobo seasoning', qty: '1 tsp' },
      { id: 'dried oregano', qty: '1/2 tsp' },
      { id: 'salt', qty: '1/2 tsp' },
      { id: 'freshly cracked black pepper', qty: '1/4 tsp' },
      { id: 'brown lentils, rinsed', qty: '1/2 cup' },
      { id: '15oz. can black beans, drained & rinsed', qty: '1' },
      { id: '14.5oz. can fire roasted tomatoes', qty: '1' },
      { id: 'frozen corn', qty: '1 cup' },
      { id: 'vegetable broth', qty: '2 cups' },
      { id: 'dry brown rice, rinsed', qty: '3/4 cup' },
      { id: 'shredded cheddar cheese', qty: '1/2 cup' },
      { id: 'green onions, sliced', qty: '2' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  spanish_chickpeas_and_rice: {
    name: 'Spanish Chickpeas and Rice',
    servings: 4,
    rank: 'B',
    _ingredients: [
      { id: 'olive oil', qty: '2 Tbsp' },
      { id: 'garlic', qty: '2 cloves' },
      { id: 'smoked paprika', qty: '1/2 Tbsp' },
      { id: 'ground cumin', qty: '1 tsp' },
      { id: 'dried oregano', qty: '1/2 tsp' },
      { id: 'cayenne pepper', qty: '1/4 tsp' },
      { id: 'Freshly cracked black pepper', qty: '' },
      { id: 'yellow onion', qty: '1' },
      { id: 'dry brown rice', qty: '1 cup' },
      { id: '15oz. can diced tomatoes', qty: '1' },
      { id: '15oz. can quartered artichoke hearts', qty: '1' },
      { id: '15oz. can chickpeas', qty: '1' },
      { id: 'vegetable broth', qty: '1 ½ cups' },
      { id: 'salt (or to taste)', qty: '1/2 tsp' },
      { id: 'fresh parsley', qty: '1/4 bunch' },
      { id: 'fresh lemon', qty: '1' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  spanish_salmon_a_la_gallega: {
    name: 'Spanish Salmon a la Gallega',
    servings: 2,
    rank: 'B',
    _ingredients: [
      { id: 'fresh salmon (400 grams)', qty: '14 oz' },
      { id: 'potatoes', qty: '2' },
      { id: 'extra virgin olive oil (30 ml)', qty: '2 tbsp' },
      { id: 'garlic', qty: '4 cloves' },
      { id: 'sweet smoked Spanish paprika (2.50 grams)', qty: '1 tsp' },
      { id: 'white wine (80 ml)', qty: '1/3 cup' },
      { id: 'finely chopped fresh parsley', qty: 'handful' },
      { id: 'sea salt', qty: 'pinch' },
      { id: 'black pepper', qty: 'dash' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  tandoori_salmon_recipe_indian_salmon_recipe: {
    name: 'Tandoori Salmon Recipe (Indian Salmon Recipe)',
    servings: 4,
    rank: 'B',
    _ingredients: [
      { id: '⅕ lbs. Boneless Salmon fillets (550 grams)', qty: '1' },
      { id: 'salt (adjust to taste)', qty: '⅓ to ½ teaspoon' },
      { id: 'turmeric', qty: '⅛ teaspoon' },
      { id: 'Kashmiri Red Chilli Powder (adjust to taste)', qty: '½ to 1 tablespoon' },
      { id: 'garam masala', qty: '1 to 1¼ teaspoon' },
      { id: 'cumin powder', qty: '½ to 1 teaspoon' },
      { id: 'coriander powder', qty: '1 to 1¼ teaspoon' },
      { id: 'garlic powder (or 1 teaspoon garlic paste)', qty: '½ teaspoon' },
      { id: 'ginger powder (or ½ teaspoon ginger paste)', qty: '¼ teaspoon' },
      { id: 'lemon juice (or lime juice)', qty: '1 tablespoon' },
      { id: 'oil (olive oil/mustard oil/avocado oil or any)', qty: '1 tablespoon' },
      { id: 'ground black pepper (optional)', qty: '¼ teaspoon' },
      { id: 'Chaat masala (or ¾ tablespoon more lemon juice or ½ tsp amchur powder + ¼ tsp cumin powder)', qty: '¾ teaspoon' },
      { id: 'Kasuri methi (dried fenugreek leaves)', qty: '1 tablespoon' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  thai_chilli_basil_chicken: {
    name: 'Thai Chilli Basil Chicken',
    servings: 2,
    rank: 'A',
    _ingredients: [
      { id: '7oz chicken thigh fillets (skinless boneless, cut into bite size pieces)', qty: '' },
      { id: 'green onion (cut into 4cm / 2" lengths.)', qty: '1' },
      { id: 'Thai basil leaves (loosely packed (Holy Basil if you can find it)', qty: '1 cup' },
      { id: 'garlic cloves (large, finely chopped)', qty: '2' },
      { id: 'birds eye or Thai chilli (deseeded and finely chopped)', qty: '1' },
      { id: 'oil (peanut, vegetable or canola)', qty: '1 1/2 tbsp' },
      { id: 'oyster sauce', qty: '2 tsp' },
      { id: 'light soy sauce', qty: '1 tsp' },
      { id: 'dark soy sauce (or all purpose)', qty: '1 tsp' },
      { id: 'maple syrup', qty: '1 tsp' },
      { id: 'water', qty: '2 tbsp' },
      { id: 'Steamed jasmine rice', qty: '' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  thai_coconut_chicken_red_curry: {
    name: 'Thai Coconut Chicken Red Curry',
    servings: 6,
    rank: 'A',
    _ingredients: [
      { id: 'boneless skinless chicken thighs', qty: '2½ lbs' },
      { id: 'green pepper', qty: '1 medium' },
      { id: 'green onions', qty: '1 bunch' },
      { id: 'carrots', qty: '3 medium' },
      { id: 'russet potatoes', qty: '2 medium' },
      { id: 'red Thai curry paste', qty: '¼ cup' },
      { id: 'light coconut milk', qty: '1 can' },
      { id: 'cumin', qty: '1 tbsp' },
      { id: 'minced ginger', qty: '1 tbsp' },
      { id: 'minced garlic', qty: '1 tbsp' },
      { id: 'brown sugar', qty: '1 tbsp' },
      { id: 'peanut butter', qty: '2 tbsp' },
      { id: 'lime juice', qty: '1½ tbsp' },
      { id: 'chicken broth', qty: '1½ cups' },
      { id: 'cornstarch (optional to thicken)', qty: '1 tbsp' },
      { id: 'dry roasted peanuts', qty: '2 tbsp' },
      { id: 'oil', qty: '1½ tbsp' },
      { id: 'dry brown rice', qty: '1.5 cups' },
      { id: 'lime (optional for garnish)', qty: '1' },
      { id: 'cilantro (optional for garnish)', qty: '1 bunch' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  thai_lettuce_wraps_larb_gai_laab_gai: {
    name: 'Thai Lettuce Wraps (Larb Gai, Laab Gai)',
    servings: 2,
    rank: 'A',
    _ingredients: [
      { id: 'cornstarch', qty: '2 tsp' },
      { id: 'water', qty: '3 tbsp' },
      { id: 'lime juice (1 to 2 limes)', qty: '2 1/2 tbsp' },
      { id: 'fish sauce', qty: '2 tbsp' },
      { id: 'brown sugar', qty: '2 tsp' },
      { id: 'avocado oil', qty: '2 tbsp' },
      { id: 'fresh ginger (grated or very finely chopped)', qty: '1 tbsp' },
      { id: 'garlic cloves (large, minced)', qty: '2' },
      { id: 'lemon grass stalk (white and very pale green part only, finely chopped', qty: '1' },
      { id: 'Thai or birds eye chili (deseeded and finely chopped', qty: '2' },
      { id: 'ground chicken', qty: '1 lb' },
      { id: 'red onion (cut into 4 wedges then finely sliced)', qty: '1/2' },
      { id: 'coriander/cilantro leaves (plus extra to garnish)', qty: '1/3 cup' },
      { id: 'mint leaves (plus extra to garnish)', qty: '1/3 cup' },
      { id: 'crushed peanuts (optional)', qty: '3 tbsp' },
      { id: '- 8 small to medium lettuce leaves (I used baby cos / romaine) (Note 3)', qty: '6' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  the_best_dal_ever: {
    name: 'The Best Dal Ever',
    servings: 4,
    rank: 'B',
    _ingredients: [
      { id: 'yellow moong dal or red split lentils', qty: '1 cup' },
      { id: 'extra-virgin olive oil', qty: '3 tablespoons' },
      { id: 'yellow onion, diced', qty: '1' },
      { id: '(2-inch) knob fresh ginger, grated', qty: '1' },
      { id: 'garlic cloves, sliced', qty: '5' },
      { id: 'ground turmeric', qty: '½ teaspoon' },
      { id: 'ground cumin', qty: '1 ½ teaspoons' },
      { id: 'ground coriander', qty: '1 teaspoon' },
      { id: 'cayenne pepper', qty: '½ teaspoon' },
      { id: 'Kosher salt and freshly ground black pepper to taste', qty: '' },
      { id: 'tomato paste', qty: '1 teaspoon' },
      { id: '(15-ounce) can diced or crushed tomatoes with their juices', qty: '1' },
      { id: '(13.5-ounce) can reduced fat coconut milk (or feel free to use full-fat if you prefer a richer dal)', qty: '1' },
      { id: 'vegetable broth', qty: '2 cups' },
      { id: 'fresh baby spinach, roughly chopped', qty: '2 cups' },
      { id: 'fresh lemon juice', qty: '1 tablespoon' },
      { id: 'dry brown rice', qty: '1 cup' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  tomato_chickpea_pasta_with_goat_cheese: {
    name: 'Tomato & Chickpea Pasta with Goat Cheese',
    servings: 6,
    rank: 'C',
    _ingredients: [
      { id: 'ounces short-cut chickpea pasta noodles', qty: '8' },
      { id: 'One 4 to 5 ounce log of goat cheese', qty: '' },
      { id: 'cloves garlic, peeled but left whole', qty: '4 medium' },
      { id: '(15 ounces) chickpeas, rinsed and drained, or 1 ½ cups cooked chickpeas', qty: '1 can' },
      { id: 'pints (4 cups) cherry tomatoes – smaller tomatoes are better!', qty: '2' },
      { id: 'Kalamata olives, pitted and roughly chopped (optional)', qty: '½ cup' },
      { id: 'extra-virgin olive oil', qty: '⅓ cup' },
      { id: 'Salt, to taste', qty: '' },
      { id: 'Freshly ground black pepper, to taste', qty: '' },
      { id: 'red pepper flakes (optional, for heat)', qty: 'Pinch of' },
      { id: 'thinly sliced fresh basil', qty: '⅓ cup' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

  turkey_bolognese_onepot_pasta: {
    name: 'Turkey Bolognese (One-Pot Pasta)',
    servings: 4,
    rank: 'A',
    _ingredients: [
      { id: '93% ground turkey', qty: '1 pound' },
      { id: 'kosher salt', qty: '1 teaspoon' },
      { id: 'extra virgin olive oil', qty: '½ tablespoon' },
      { id: 'yellow onion (chopped)', qty: '½' },
      { id: 'carrot (peeled and chopped)', qty: '1 medium' },
      { id: 'celery rib (chopped)', qty: '1' },
      { id: 'tomato paste', qty: '2 tablespoons' },
      { id: 'garlic (minced)', qty: '1 clove' },
      { id: 'ounces uncooked chickpea pasta (rigatoni)', qty: '10' },
      { id: 'canned crushed tomatoes (Tuttoroso (15 ounce can)', qty: '1 ½ cups' },
      { id: 'chicken bone broth (I used Swanson)', qty: '2 ½ cups' },
      { id: 'Calabrian chili paste (optional)', qty: '1 teaspoon' },
      { id: 'parmesan cheese (freshly grated , plus more for garnish)', qty: '¼ cup' },
      { id: 'fresh basil (for garnish)', qty: '' },
      { id: 'ricotta (optional for serving)', qty: '' },
    ],
    _totalMacros: { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, sodiumMg: 0 }, // TODO: log in Cronometer as "1.00 full recipe" and re-run sync
  },

};

// Lock _ingredients and _totalMacros on every recipe
Object.values(RECIPE_CATALOG).forEach(recipe => {
  Object.freeze(recipe._ingredients);
  Object.freeze(recipe._totalMacros);
});
